### ISSUE TITLE
Disable iiif_metadata_field config to reveal all metadata

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/essi#20]
# Summary

Essi currently only shows a subset of metadata in the UV, per a [configuration](https://github.com/scientist-softserv/essi/blob/main/config/initializers/hyrax.rb#L189-L193) + [yml file](https://github.com/scientist-softserv/essi/blob/main/config/essi_config.example.yml#L158-L172). 

Implementation: https://github.com/scientist-softserv/essi/blob/main/lib/extensions/hyrax/work_show_presenter/manifest_metadata.rb#L31 

Per #16 the ask is to show any and all available metadata in the UV pane, which may require us to undo/override what they current have. 

# Acceptance Criteria

- [ ] All metadata should display in the UV's "more information" pane. 
  - considerations may be needed for Allinson Flex

# Testing Instructions
- [ ] Create a parent work
- [ ] Create a child work. Fill out all of the available fields in the child work. 
- [ ] Attach the child work to the parent work.
- [ ] The child work's metadata should appear in the UV's "more information" side pane when the user clicks on the child.
- [ ] Confirm that IIIF Print's version of the metadata supports questioning authorities and faceted links
  - [ ] What is faceted is determined by the m3 (Allinson Flex) profile, a field such as `contributor` should render a link in the side panel
  - [ ] Verify that the rights statement field renders a human readable text and not the URI, something like "No Copyright"

# Notes

We are hopeful that if we comment out their [current implementation](https://github.com/scientist-softserv/essi/blob/main/lib/extensions/hyrax/work_show_presenter/manifest_metadata.rb#L13), it may just start working with iiif_print.

**Comment by kirkkwang** [comment]
After some research, it looks like Essi already pulls all the metadata from the AllinsonFlex fields and also additional ones for their metadata.  In this part of the [code](https://github.com/IU-Libraries-Joint-Development/essi/blob/test-iiif_print/lib/extensions/hyrax/work_show_presenter/manifest_metadata.rb#L36), Essi uses the #dynamic_schema_service method that essentially returns data similar to IIIF Print's AllinsonFlex [query](https://github.com/scientist-softserv/iiif_print/blob/main/lib/iiif_print.rb#L189-L193).  I haven't been able to get the `indexing` data easily from using that and other methods however.  IIIF Print's query allows us to see if the field is facetable which indicates if we should render the facet links or not.

The way IIIF Print displays the metadata is not in an intentional or meaningful order:

![Image](https://user-images.githubusercontent.com/19597776/235226968-7591ecc4-e69a-4f83-8e4b-facb14e11ce0.png)

The order is actually determined by how the m3 profile is set up:

![Image](https://user-images.githubusercontent.com/19597776/235227406-ebc2739f-9408-43a8-9a27-598d0e7c0dfc.png)

NOTE: some of the fields are not shown because they are "admin_only"

This lack of intentional sorting persists as well in the child metadata.  **A possible solution** to this could be getting a sort order like how Essi does it through their [yml](https://github.com/IU-Libraries-Joint-Development/essi/blob/main/config/essi_config.docker.yml#L158-L172) and feeding it into the Hyrax [config](https://github.com/IU-Libraries-Joint-Development/essi/blob/main/config/initializers/hyrax.rb#L189-L193).  We can probably make a configuration to add these fields in an controlled order.

IIIF Print's implementation does pull some extra fields but I'm unsure if this is desired behavior:

![Image](https://user-images.githubusercontent.com/19597776/235225844-c27adc1e-2aa3-48e2-bb1d-076086d4f264.png)

The `title` is essentially there twice (under different labels) and `creator` is there three times

Here's Essi's example:

![Image](https://user-images.githubusercontent.com/19597776/235226206-61515cfe-427a-4a2f-b3d5-745f9405d08f.png)

**Comment by ShanaLMoore** [comment]
~~Blocked from merging due to failing spec~~

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- parent work: https://dcadmin-test.dlib.indiana.edu/concern/scientifics/st74cq441?locale=en
- child work: https://dcadmin-test.dlib.indiana.edu/concern/bib_records/79407x16z?locale=en

<details><summary>From the UV, clicking a child work and viewing "More Information" side panel will show both the parent and child metadata. Questioning authority metadata navigates to external link. Faceted metadata navigates to a catalog search for that search query.</summary>

![Scientific parent work ID st74cq441 Digital Collections 2023-05-10 at 12 40 34 PM](https://github.com/scientist-softserv/essi/assets/29311858/136925ce-6852-493d-bad3-16914f390ab8)
</details>
